config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/about',     to: 'static_pages#about'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { in: 6..200 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    redirect_to root_path unless logged_in?
    @post = Post.new(
        user_id: current_user.id,
        content: params[:post][:content])
    if @post.save
      redirect_to posts_path
      flash[:success] = "Post was successfully created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
  end

  def update
  end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination. Please try again"
    render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
   @user = User.find(params[:id])
  end

  def create
    @user =User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Congratulations, you're now a member, #{@user[:name]}!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Members-only</a>
     assignment from <a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication">The Odin Project</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", 'https://github.com/dvik1950' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Members only", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Posts",   posts_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<ul id="posts">
  <% @posts.each do |post| %>
    <ol class="posts">
      <li class="list-group-item">
    <li id="post-<%= post.id %>">
      <center>
    <%if logged_in? %>
     <h1> <span class="user"><%= link_to post.user.name, post.user %></span> wrote: </h1>
        <%else%>
      <h1>  <span class="user">Anonymous wrote:  </span> </h1>
      <% end %>
     <h3> <span class="content"><%= post.content %></span> </h3>
      <span class="timestamp">
     <%= time_ago_in_words(post.created_at) %> ago.
  </span>
      </center>
    </li>
      </li>
  <% end %>
  </ol>
</ul>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>


      <%= f.submit "Submit post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<ul id="posts">

    <li id="post-<%= @post.id %>">
      <%if logged_in? %>
        <%= gravatar_for @post.user %>
        <span class="user"><%= link_to @post.user.name, @post.user %></span> wrote: "
      <%else%>
        <span class="user">Anonymous wrote: " </span>
      <% end %>
      <span class="content"><%= @post.content %></span> "
      <span class="timestamp">
     <%= time_ago_in_words(@post.created_at) %> ago.
  </span>
    </li>

</ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<center><h1>About the project</h1>
<p>Members-only is an website where everyone can see posts but only logged in users can see the authors of the posts. This is an assignment from The Odin Project.</p>
<p>The layout is a copy of the Sample App from Michael Hartl's Ruby on Rails tutorial.</p>
</center>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Members-only</h1>
  <h3>A website to dedicated to trash talking</h3>
  <% if logged_in? %>
    <%= link_to "Make a post!", new_post_path, class: "btn btn-lg btn-primary" %>
    <%else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <%end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>